baseURL = "https://competent-shannon-047a89.netlify.com/"
languageCode = "en-us"
title = "Caramel"
theme = "aether"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "friendly"
    tabWidth = 4